## Objected oriented approach in turtle; In turtle module we have a class "Turtle".
import turtle
# from turtle import Turtle
# import turtle as t // aliasing turtle module as t and used it later as t.turtle() i.e(module.class())
'''
from turtle import*
abc = Turtle()
forward(100)
exitonclick()
'''
#s1 = screen()
#s1.mainloop()   or   s1.exitonclick()
abc = turtle.Turtle()
abc.speed(1)
abc.shape("turtle")
abc.color("red", "Green")
# abc.pencolor("green")
# abc.fillcolor("yellow")
turtle.bgcolor("black")
abc.penup()
abc.fd(100)
abc.pendown()
abc.begin_fill()
abc.circle(150)
abc.end_fill()
abc.penup()
abc.bk(100)
abc.pendown()
abc.color("blue", "pink")
abc.begin_fill()
abc.circle(50)
abc.end_fill()
abc.penup()
abc.fd(100)
abc.pendown()
abc.color("red", "yellow")
abc.begin_fill()
abc.circle(50)
abc.end_fill()
abc.penup()
abc.fd(100)
abc.pendown()
abc.color("cyan", "orange")
abc.begin_fill()
abc.circle(50)
abc.end_fill()
abc.penup()
abc.lt(90)
abc.fd(100)
abc.rt(90)
abc.lt(90)
abc.pendown()
abc.pensize(35)
abc.hideturtle()
print(abc.isvisible())
abc.fd(100)
abc.lt(90)
abc.fd(200)
abc.lt(90)
abc.fd(100)
abc.lt(90)
abc.fd(200)
print(abc.pos())
abc.goto(x=-15,y=-15)
print(abc.isdown())
abc.showturtle()
abc.screen.mainloop()  # instance of screen class
# turtle.exitonclick()
